name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements/*.txt
            tox.ini

      - name: Install requirements
        run: make install

      - name: Run linters
        run: make lint
