name: Python tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        postgres-image:
          - "postgres:12"
          - "postgres:13"
          - "postgres:14"
          - "postgres:15"
          - "postgres:16"

    services:
      postgres:
        image: ${{ matrix.postgres-image }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: make install

      - name: Run the tests
        run: tox --parallel --parallel-no-spinner
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/django_integrity
