name: Python tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        postgres-image:
          - "postgres:14"
          - "postgres:15"
          - "postgres:16"
          - "postgres:17"
          - "postgres:18"

    services:
      postgres:
        image: ${{ matrix.postgres-image }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up Python versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13
            3.14
          allow-prereleases: true
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            uv.lock
            tox.ini

      - name: Make a virtualenv
        run: python3 -m venv .venv

      - name: Install requirements
        run: |
          source .venv/bin/activate
          pip install --group tox

      - name: Run the tests
        run: |
          source .venv/bin/activate
          tox --parallel --parallel-no-spinner --skip-missing-interpreters=false
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/django_integrity

  validate_commits:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    # Only check commits on PR branches, where they can be changed.
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: |
          git fetch origin main
          git branch main origin/main
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: pip install validate_commits
      - run: validate-commits
