name: Python tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        postgres-image:
          - "postgres:12"
          - "postgres:13"
          - "postgres:14"
          - "postgres:15"
          - "postgres:16"

    services:
      postgres:
        image: ${{ matrix.postgres-image }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up Python versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.11
            3.10
          cache: 'pip'

      - name: Install tox
        run: pip install tox

      - name: Run the tests
        run: tox --parallel --parallel-no-spinner --skip-missing-interpreters=false
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/django_integrity
